name: LGTM Auto Approve

on:
  issue_comment:
    types: [created]

jobs:
  approve:
    if: contains(github.event.comment.body, '/approve')
    runs-on: ubuntu-latest
    steps:
      - name: Approve Pull Request
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          echo "Approving PR #$PR_NUMBER"
          RESPONSE=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews \
            -d '{"event":"APPROVE"}')
          echo "Response: $RESPONSE"
